### ISSUE TITLE
Error of using clip mapping

### ISSUE THREAD

**Issue by dxue321** [hyp-nerf/HyP-NeRF#1]
When I train the network with "--clip_mapping", I get an error. It seems the dimension of the tensor input to CLIP is wrong.
python main_nerf.py './data/abo' --bound 1.0 --scale 0.8 --dt_gamma 0 --class_choice CHAIR --load_ckpt --clip_mapping

  File "main_nerf.py", line 117, in <module>
    trainer.train(train_loader, valid_loader, 2000)
  File "/home/dx/code/video/HyP-NeRF/nerf/utils.py", line 597, in train
    self.train_one_epoch(train_loader)
  File "/home/dx/code/video/HyP-NeRF/nerf/utils.py", line 701, in train_one_epoch
    preds, truths, loss = self.train_step(data)
  File "/home/dx/code/video/HyP-NeRF/nerf/utils.py", line 476, in train_step
    outputs = self.model(index, data, rays_o, rays_d, staged=False, bg_color=bg_color, perturb=True, force_all_rays=False if self.opt.patch_size == 1 else True, **vars(self.opt))
  File "/home/dx/anaconda3/envs/video/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dx/code/video/HyP-NeRF/nerf/network_fcblock.py", line 242, in forward
    clip_output = self.run_clip_mapping(idx, input_dict)
  File "/home/dx/code/video/HyP-NeRF/nerf/network_fcblock.py", line 222, in run_clip_mapping
    img_input = input_dict['img_original'].permute(0,-1,1,2)
RuntimeError: number of dims don't match in permute

**Comment by vanhalen42** [comment]
Could you tell me what value you are getting for `input_dict['img_original'].shape` [here](https://github.com/hyp-nerf/HyP-NeRF/blob/4a67bb7907ed28d4e3beca72ea21e7e07a47430d/nerf/network_fcblock.py#L222)?

**Comment by dxue321** [comment]
> Could you tell me what value you are getting for `input_dict['img_original'].shape` [here](https://github.com/hyp-nerf/HyP-NeRF/blob/4a67bb7907ed28d4e3beca72ea21e7e07a47430d/nerf/network_fcblock.py#L222)?

The shape is [1, 4096, 3].

**Comment by vanhalen42** [comment]
I have created a separate branch ([vanhalen42-provider-clip-fix](https://github.com/hyp-nerf/HyP-NeRF/tree/vanhalen42-provider-clip-fix)) with the fix. Please let me know if it fixes the issue.

**Comment by dxue321** [comment]
> I have created a separate branch ([vanhalen42-provider-clip-fix](https://github.com/hyp-nerf/HyP-NeRF/tree/vanhalen42-provider-clip-fix)) with the fix. Please let me know if it fixes the issue.

Hi, thanks for the effort. The size problem has been fixed, but I still can't train the model with "--clip_mapping". 
Could you please explain when should I apply "--clip_mapping"? during training? or you haven't release the training code with clip? Since in the forward function of the network, if clip_mapping==True, the network does forward without gradient. I feel a bit confused about this part.

**Comment by vanhalen42** [comment]
Yes, the training code with CLIP has yet to be fully released. The query network (i.e. clip mapping) is trained after training HyP-NeRF (using the standard training procedure). The codebook of the pre-trained Hypernetwork acts as the supervision for the query network. The query network is trained to predict a vector in the space of the pre-trained codebook vectors, given a CLIP embedding, by minimizing the L2 loss between the prediction and the pre-trained codebook vector.

**Comment by dxue321** [comment]
Get it, thanks!

> Yes, the training code with CLIP has yet to be fully released. The query network (i.e. clip mapping) is trained after training HyP-NeRF (using the standard training procedure). The codebook of the pre-trained Hypernetwork acts as the supervision for the query network. The query network is trained to predict a vector in the space of the pre-trained codebook vectors, given a CLIP embedding, by minimizing the L2 loss between the prediction and the pre-trained codebook vector.
